### ISSUE TITLE
Overuse of _onMoveEnd, perhaps another event could be used/handled

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/MapML-Leaflet-Plugin#24]
The MapMLLayer executes _tileLayer._onMoveEnd when the response with tile urls is received.  Instead of doing that, it should probably do something less drastic, because it is the second iteration of that handler, the first being actually in response to the end of the map moving.  To accommodate the side effects of this,  one has to set map option.fadeAnimation = false.   There has to be a way to have cake and eat it too! 
https://github.com/Maps4HTML/Web-Map-Custom-Element/commit/1a5f369297f7ff87ece297bc358eeef5ac7336dc

**Comment by mapmeld** [comment]
I saw MapML this morning on the grassroots-mapping e-mail list. Interested in how I can help.

I wonder if you could re-evaluate how MapML handles tiles. Currently the Leaflet client extends all of L.tileLayer to accept the MapML tile definition URL http://geogratis.gc.ca/mapml/osm/ and _onMoveEnd refreshes the map a lot.  I understand that this is helpful for supporting several other types of layers, but tile layers need only a coordinate system and a URL template. 

These are some different ways to handle it:

- M.MapMLTileLayer could have a variable like this.loading = true, and then once the tile URL is known, change how _onMoveEnd() works so there are no more repeated layer resets
- M.MapMLTileLayer could be a smaller class which finds out the true tile URL asynchronously, and then creates a standard L.tileLayer object. You could use a callback to return the internal tile layer to the user, or connect key functions and events: ```this.remove = function() { /* special code */ this._standardTileLayer.remove(); }```
- M.MapMLTileLayer could accept XYZ tile format strings, as they're really common
- the MapML tile definition on the server could be MapBox TileJSON format or other standard

**Comment by prushforth** [comment]
Hi Nick,  

Thanks for your interest and support.  The idea behind MapML is to wrap all the semantics of maps into the format while at the same time maintaining access to the DOM of the map document, mostly so that it can be addressed and styled by CSS.  The eventual consumer of MapML will not be javascript but the actual browser so it should be less of a culture shock to those programmers.

So, what I was trying to do was treat every MapML layer like it could return tiles, vectors or images in any given response.  To do that I created three layer types M.MapML (poor name, should be M.VectorLayer or similar), M.MapMLTileLayer and M.ImageLayer (currently working on this locally).  

Instances of these layer types 'could be' present in any mapml response, and so are sub-layers of the M.MapMLLayer, all under the management of the M.MapMLLayer.  I’m not certain I’ve got the code in the right configuration yet.  I started coding at Leaflet 0.7.4 and upgraded to 1.x at one point, so there may still be vestiges of Leaflet 0.7  related code.

The reason I created this issue is because I thought there might be a way of triggering an event (line 304 of mapml.js) instead of invoking the event handler directly once all the tile urls are known.  The tile urls become known asynchronously, because it is at the end of an xhr call, having parsed and read all the tile urls, that the _onMoveEnd handler is directly called.  I imagine this is horrible practice, but TBH I am a JS newbie. Also, the polymer Web component depends on methods in these classes, so things may be a bit ‘delicate’ unfortunately.  Automated testing is also high on the TODO list.

> M.MapMLTileLayer could have a variable like this.loading = true, and then once the tile URL is known, change how _onMoveEnd() works so there are no more repeated layer resets
I was thinking that since the _onMoveEnd would have been invoked previously by the actual moveend event, it would almost certainly be better to only do the work that is required to display the tiles and not repeat the _onMoveEnd logic.  Your suggestions make me think about this issue again, thank you.  Ideally, it would be the M.MapMLLayer that receives events from the map and dispatches the appropriate sub-layer method calls / events.  I am not sure I’ve got this right yet.

> M.MapMLTileLayer could be a smaller class which finds out the true tile URL asynchronously, and then creates a standard L.tileLayer object. You could use a callback to return the internal tile layer to the user, or connect key functions and events: this.remove = function() { /* special code */ this._standardTileLayer.remove(); }
Not sure I understand this idea yet.  Can you elaborate a bit, please?  With the organization invite, you can create repos which could be used for pull requests against the principle repos here.  Not quite certain what the best workflow is, as I am also a github newbie :-).

> the MapML tile definition on the server could be MapBox TileJSON format or other standard
Interesting idea.  URL templates are in scope for servers, but out of scope for clients

> M.MapMLTileLayer could accept XYZ tile format strings, as they're really common
On the client, I am strictly trying to avoid that.  One key requirement for adoption by browsers IMHO is to rely on URLs, not recipes, to the greatest extent possible.   I have used URL templates in the web.xml of the MapMLServer servlet.  A more sophisticated configuration format like the TileJSON could be interesting (indeed for a more sophisticated server!).

Cheers,
Peter

**Comment by prushforth** [comment]
Fixed by https://github.com/Maps4HTML/MapML-Leaflet-Plugin/pull/45
